version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABSE}
    ports:
      - ${PGPORT}:5432
    volumes:
      - ./db:/var/lib/postgresql